name: Mirror to Codeberg

on:
  push:
    branches:
      - main   # change if your default branch is different

jobs:
  mirror:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for full mirror

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEBERG_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Trim Codeberg note from README
        run: |
          sed -i '/^> \[!NOTE\]/,/^$/d' README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "trim Codeberg mirror note for Codeberg"

      - name: Mirror push to Codeberg
        run: |
          git remote add codeberg git@codeberg.org:DavidBalishyan/betterfetch.git
          git push --mirror codeberg

